#!/bin/bash
CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

DJANGODIR=$CURRENT_DIR/../
SOCKFILE=$CURRENT_DIR/../run/gunicorn.sock
NUM_WORKERS=3
DJANGO_SETTINGS_MODULE=moneykeeper.settings
DJANGO_WSGI_MODULE=moneykeeper.wsgi

cd $DJANGODIR
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

exec /usr/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --workers $NUM_WORKERS \
  --bind=unix:$SOCKFILE \
  --log-level=info \
  --log-file=-
