- hosts: all
  vars:
    projectdir: /var/www/MoneyKeeper
    localprojectdir: /home/ilov3/dev/MoneyKeeper
  tasks:

  - name: Build static
    local_action: shell gulp build --production
                  chdir={{localprojectdir}}

  - name: Push static to server
    local_action: shell scp staticdev/js/project.min.js moneykeeper:{{projectdir}}/static/js/ &&
                        scp staticdev/js/thirdparty.min.js moneykeeper:{{projectdir}}/static/js/ &&
                        scp staticdev/css/all.min.css moneykeeper:{{projectdir}}/static/css/
                  chdir={{localprojectdir}}

  - name: Update repo
    shell: git pull
           chdir={{projectdir}}

  - name: Migrate app
    shell: python manage.py migrate
           chdir={{projectdir}}

  - name: Collect static
    shell: python manage.py collectstatic --no-input
           chdir={{projectdir}}

  - name: Restart gunicorn
    shell: supervisorctl restart moneykeeper
    become: yes

  - name: Restart nginx
    shell: service nginx restart
    become: yes
